### ISSUE TITLE
"-" in package name problem

### ISSUE THREAD

**Issue by njxqlus** [melihovv/laravel-package-generator#3]
When using "-" symbol in package name, like "some-package" it create class, namespace and other with name "some-package".
Btw, maybe Capitalize class names?

**Comment by melihovv** [comment]
You should use
```
php artisan package:new Melihovv SomePackage
```
instead of
```
php artisan package:new Melihovv some-package
```
The first command will create `packages/melihovv/some-package` folder and will use Melihovv and SomePackage names in skeleton templates.

If you want to override default convention, you can provide `-i` flag to command. For example, you want package `melihovv/some-package` in `packages/melihovv/yet-another-package` folder. Run
```
➜  laravel-starter-kit git:(master) ✗ ar package:new Melihovv SomePackage -i

 The vendor name? [Melihovv]:
 > 

 The package name? [SomePackage]:
 > 

 The vendor folder name? [melihovv]:
 > 

 The package folder name? [some-package]:
 > yet-another-package
```
