### ISSUE TITLE
Error on Test

### ISSUE THREAD

**Issue by abkrim** [melihovv/laravel-package-generator#7]
Hi.

I've a problem with test create for your package.

Error
```php
public function testExample()
{
    assertEquals(1, 1); 
}
```

Must be
```php
public function testExample()
{
    $this->assertEquals(1, 1);
}
```

Also better if use Orchestra\Testbench, package must be some changes for work.

composer.json of Laravel ad options symlink ture.
```json
"repositories": [
        {
            "type": "path",
            "url": "packages/vendor/my-package",
            "options": {
                "symlink": true
            }
        }
    ]
```

And require, 
```
"orchestra/testbench": "^3.6",
"orchestra/testbench-dusk": "^3.5",
```

Best reagds. And thanks for yoy generator. 

Sorry if not send a PR but I don't expertise with git

**Comment by abkrim** [comment]
Ohh sorry ... i work with test on vendor/developer/package instead ...package...

**Comment by melihovv** [comment]
Hello, @abkrim.
Yes, you are right about `assertEquals(1, 1);` must be `$this->assertEquals(1, 1);`. I fixed it, thanks.

What about second issue - currenly there is no possibility to check if orchestra/testbench is installed and depends on that use it or not. It is because generated package has own composer autoloading.

It would be nice if there were ability to override stubs folder in config as skeleton one. I accept PR for that.
